// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/setcreed/kshop/app/user/service/internal/conf"
	"github.com/setcreed/kshop/app/user/service/internal/server"
	"github.com/setcreed/kshop/app/user/service/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	userService := service.NewUserService(logger)
	grpcServer := server.NewGRPCServer(confServer, tracerProvider, logger, userService)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
