// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/setcreed/kshop/app/shop/interface/internal/biz"
	"github.com/setcreed/kshop/app/shop/interface/internal/conf"
	"github.com/setcreed/kshop/app/shop/interface/internal/data"
	"github.com/setcreed/kshop/app/shop/interface/internal/server"
	"github.com/setcreed/kshop/app/shop/interface/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	client := data.NewRedis(confData)
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(discovery)
	dataData, cleanup, err := data.NewData(confData, client, logger, userClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	shopInterface := service.NewShopInterface(userUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, auth, shopInterface, logger, tracerProvider)
	grpcServer := server.NewGRPCServer(confServer, shopInterface, logger, tracerProvider)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
