// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMobile holds the string denoting the mobile field in the database.
	FieldMobile = "mobile"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldNickName holds the string denoting the nick_name field in the database.
	FieldNickName = "nick_name"
	// FieldHeadURL holds the string denoting the head_url field in the database.
	FieldHeadURL = "head_url"
	// FieldBirthday holds the string denoting the birthday field in the database.
	FieldBirthday = "birthday"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldMobile,
	FieldPassword,
	FieldNickName,
	FieldHeadURL,
	FieldBirthday,
	FieldAddress,
	FieldDesc,
	FieldGender,
	FieldRole,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// NickNameValidator is a validator for the "nick_name" field. It is called by the builders before save.
	NickNameValidator func(string) error
	// HeadURLValidator is a validator for the "head_url" field. It is called by the builders before save.
	HeadURLValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole int
)
